"""empty message

Revision ID: 96bb4d026e5f
Revises: d0754f7cec41
Create Date: 2019-11-09 00:51:24.422189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96bb4d026e5f'
down_revision = 'd0754f7cec41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicine', sa.Column('medicines', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'medicine', 'clinic', ['medicines'], ['clinic_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'medicine', type_='foreignkey')
    op.drop_column('medicine', 'medicines')
    # ### end Alembic commands ###
