"""empty message

Revision ID: d0754f7cec41
Revises: 
Create Date: 2019-11-09 00:35:42.920543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0754f7cec41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cages',
    sa.Column('cage_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('emptiness', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('cage_id')
    )
    op.create_table('clinic',
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('contact_info', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('clinic_id')
    )
    op.create_table('medicine',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.Column('barcode_number', sa.String(length=60), nullable=False),
    sa.Column('serial_number', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('serial_number'),
    sa.UniqueConstraint('barcode_number'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('owner',
    sa.Column('ssn', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sex', sa.String(length=5), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('address', sa.String(length=60), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ssn'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('staff',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('staff_id')
    )
    op.create_table('treatment',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('appointment',
    sa.Column('appo_id', sa.Integer(), nullable=True),
    sa.Column('on', sa.DateTime(), nullable=False),
    sa.Column('appo_type', sa.String(), nullable=False),
    sa.Column('ssn', sa.Integer(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ssn'], ['owner.ssn'], ),
    sa.PrimaryKeyConstraint('ssn')
    )
    op.create_table('cage_notes',
    sa.Column('cage_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cage_id'], ['cages.cage_id'], ),
    sa.PrimaryKeyConstraint('cage_id', 'note')
    )
    op.create_table('invoices',
    sa.Column('serial_number', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('ssn', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ssn'], ['owner.ssn'], ),
    sa.PrimaryKeyConstraint('serial_number')
    )
    op.create_table('pet',
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('checkin_date', sa.DateTime(), nullable=True),
    sa.Column('checkout_date', sa.DateTime(), nullable=True),
    sa.Column('specy', sa.String(length=60), nullable=True),
    sa.Column('race', sa.String(length=60), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('ssn', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ssn'], ['owner.ssn'], ),
    sa.PrimaryKeyConstraint('pet_id')
    )
    op.create_table('suitability',
    sa.Column('cage_id', sa.Integer(), nullable=False),
    sa.Column('suitable', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cage_id'], ['cages.cage_id'], ),
    sa.PrimaryKeyConstraint('cage_id', 'suitable')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('disability',
    sa.Column('pet', sa.Integer(), nullable=False),
    sa.Column('disab_desc', sa.String(length=260), nullable=False),
    sa.ForeignKeyConstraint(['pet'], ['pet.pet_id'], ),
    sa.PrimaryKeyConstraint('pet', 'disab_desc')
    )
    op.create_table('pet_notes',
    sa.Column('pet', sa.Integer(), nullable=False),
    sa.Column('note_desc', sa.String(length=260), nullable=False),
    sa.ForeignKeyConstraint(['pet'], ['pet.pet_id'], ),
    sa.PrimaryKeyConstraint('pet', 'note_desc')
    )
    op.create_table('vet',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('staff_id')
    )
    op.create_table('assistant',
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=60), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['vet.staff_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('staff_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assistant')
    op.drop_table('vet')
    op.drop_table('pet_notes')
    op.drop_table('disability')
    op.drop_table('user')
    op.drop_table('suitability')
    op.drop_table('pet')
    op.drop_table('invoices')
    op.drop_table('cage_notes')
    op.drop_table('appointment')
    op.drop_table('treatment')
    op.drop_table('staff')
    op.drop_table('owner')
    op.drop_table('medicine')
    op.drop_table('clinic')
    op.drop_table('cages')
    # ### end Alembic commands ###
